name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.compiler.cc }} build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }

      fail-fast: false

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - uses: actions/checkout@v2

      - name: compiler version
        run: ${{ matrix.compiler.cc }} --version

      - name: make
        run: make
